# Generated by Django 3.0.4 on 2020-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scoringModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoringNumber', models.IntegerField()),
                ('client', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_key', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
