# Generated by Django 3.0.4 on 2020-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexModules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.TextField()),
                ('round', models.IntegerField()),
                ('state_column', models.CharField(blank=True, max_length=255, null=True)),
                ('form_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sheetsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.TextField()),
                ('round', models.IntegerField()),
                ('state_column', models.CharField(max_length=255)),
                ('form_link', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='scoringNumber',
        ),
    ]
