# Generated by Django 3.0.4 on 2020-04-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexModules', '0002_auto_20200403_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sheetsModel',
            new_name='submissionModel',
        ),
    ]
