# Generated by Django 3.0.4 on 2020-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubemodel',
            name='chat',
            field=models.TextField(blank=True),
        ),
    ]
