# Generated by Django 3.0.4 on 2020-04-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_leader_github', models.CharField(max_length=255)),
                ('member1_github', models.CharField(max_length=255)),
                ('member2_github', models.CharField(blank=True, max_length=255, null=True)),
                ('member3_github', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='phaseSelectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.BooleanField(default=True)),
                ('section2', models.BooleanField(default=False)),
                ('section3', models.BooleanField(default=False)),
                ('section4', models.BooleanField(default=False)),
                ('final', models.BooleanField(default=False)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='manageTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('j', 'judge'), ('o', 'organiser'), ('m', 'mentor')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
