# Generated by Django 3.0.4 on 2020-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_leader_github', models.CharField(max_length=255)),
                ('team_leader_email', models.CharField(max_length=255)),
                ('member1_github', models.CharField(max_length=255)),
                ('member1_email', models.CharField(max_length=255)),
                ('member2_github', models.CharField(blank=True, max_length=255, null=True)),
                ('member2_email', models.CharField(blank=True, max_length=255, null=True)),
                ('member3_github', models.CharField(blank=True, max_length=255, null=True)),
                ('member3_email', models.CharField(blank=True, max_length=255, null=True)),
                ('member4_github', models.CharField(blank=True, max_length=255, null=True)),
                ('member4_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
