# Generated by Django 3.0.4 on 2020-03-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_manageteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member4_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member4_github',
        ),
    ]
