# Generated by Django 3.0.4 on 2020-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200330_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member1_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member3_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_email',
        ),
    ]
